import { z } from "zod";
import { DEFAULT_LIMIT, DEFAULT_MAX_PAGES, MAX_PAGES, MAX_WHOOP_LIMIT } from "../constants.js";

export const ResponseFormatSchema = z.enum(["markdown", "json"]).default("markdown");
export const PrivacyModeValueSchema = z.enum(["summary", "structured", "raw"]);
export const PrivacyModeSchema = PrivacyModeValueSchema.optional()
  .describe("Optional per-call payload privacy override. Defaults to WHOOP_PRIVACY_MODE or structured. raw returns full WHOOP API payloads.");

export const DateTimeSchema = z.string()
  .datetime({ offset: true })
  .optional()
  .describe("ISO 8601 date-time with timezone, e.g. 2026-04-30T00:00:00Z");

export const CollectionInputSchema = z.object({
  start: DateTimeSchema,
  end: DateTimeSchema,
  limit: z.number().int().min(1).max(MAX_WHOOP_LIMIT).default(DEFAULT_LIMIT)
    .describe("WHOOP page size. WHOOP allows a maximum of 25."),
  next_token: z.string().optional().describe("WHOOP pagination token returned by a previous call."),
  all_pages: z.boolean().default(false).describe("Fetch multiple pages up to max_pages."),
  max_pages: z.number().int().min(1).max(MAX_PAGES).default(DEFAULT_MAX_PAGES)
    .describe("Maximum pages to fetch when all_pages is true."),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const IdInputSchema = z.object({
  id: z.union([z.string().min(1), z.number().int().positive()]).describe("WHOOP resource id."),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const SimpleReadInputSchema = z.object({
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const ResponseOnlyInputSchema = z.object({
  response_format: ResponseFormatSchema
}).strict();

export const AuthUrlInputSchema = z.object({
  state: z.string().max(500).optional().describe("Optional OAuth state value generated by the caller."),
  scopes: z.array(z.string()).optional().describe("Optional scope override. Defaults to all read-only WHOOP scopes used by this server."),
  response_format: ResponseFormatSchema
}).strict();

export const ExchangeCodeInputSchema = z.object({
  code: z.string().min(1).describe("OAuth authorization code, or a full redirect URL containing ?code=..."),
  response_format: ResponseFormatSchema
}).strict();

export const DailySummaryInputSchema = z.object({
  days: z.number().int().min(7).max(30).default(10)
    .describe("Lookback window used to build the daily baseline. Minimum 7, maximum 30."),
  timezone: z.string().min(1).max(80).default("UTC")
    .describe("IANA timezone used only for display, e.g. America/New_York."),
  response_format: ResponseFormatSchema
}).strict();

export const WeeklySummaryInputSchema = z.object({
  days: z.number().int().min(7).max(30).default(7)
    .describe("Recent analysis window in days."),
  compare_days: z.number().int().min(0).max(30).default(7)
    .describe("Prior comparison window in days. Use 0 to disable comparison."),
  timezone: z.string().min(1).max(80).default("UTC")
    .describe("IANA timezone used only for display, e.g. America/New_York."),
  response_format: ResponseFormatSchema
}).strict();

export const AuthUrlOutputSchema = z.object({
  auth_url: z.string(),
  redirect_uri: z.string(),
  scopes: z.array(z.string()),
  next_step: z.string()
}).strict();

export const ExchangeCodeOutputSchema = z.object({
  ok: z.boolean(),
  token_path: z.string(),
  scope: z.string().optional(),
  expires_at: z.number().optional(),
  note: z.string()
}).strict();

export const EndpointDataOutputSchema = z.object({
  endpoint: z.string(),
  privacy_mode: PrivacyModeValueSchema,
  data: z.unknown()
}).strict();

export const CollectionOutputSchema = z.object({
  endpoint: z.string(),
  privacy_mode: PrivacyModeValueSchema,
  count: z.number().int().nonnegative(),
  records: z.array(z.unknown()),
  next_token: z.string().optional(),
  has_more: z.boolean(),
  pages_fetched: z.number().int().nonnegative()
}).strict();

export const CacheStatusOutputSchema = z.object({
  enabled: z.boolean(),
  path: z.string(),
  entries: z.number().int().nonnegative(),
  newest_cached_at: z.string().optional()
}).strict();

export const RevokeAccessOutputSchema = z.object({
  ok: z.boolean(),
  token_path: z.string(),
  local_tokens_cleared: z.boolean(),
  note: z.string()
}).strict();

export const PrivacyAuditOutputSchema = z.object({
  project: z.string(),
  unofficial: z.boolean(),
  privacy_mode_default: PrivacyModeValueSchema,
  raw_payloads_opt_in: z.boolean(),
  cache_enabled: z.boolean(),
  cache_path: z.string(),
  token_path: z.string(),
  stdout_safe: z.boolean(),
  secret_env_vars: z.array(z.string()),
  required_env_present: z.record(z.boolean()),
  redacted_key_patterns: z.array(z.string()),
  notes: z.array(z.string())
}).strict();

export const ConnectionStatusOutputSchema = z.object({
  ok: z.boolean(),
  ready_for_whoop_api: z.boolean(),
  node: z.object({
    version: z.string(),
    supported: z.boolean()
  }).strict(),
  privacy_mode: PrivacyModeValueSchema,
  required_env: z.record(z.boolean()),
  missing_env: z.array(z.string()),
  redirect_uri: z.string().optional(),
  automatic_auth_supported: z.boolean(),
  token: z.object({
    path: z.string(),
    exists: z.boolean(),
    readable: z.boolean(),
    permissions: z.string().optional(),
    secure_permissions: z.boolean().optional(),
    expires_at: z.number().optional(),
    expired: z.boolean().optional(),
    has_refresh_token: z.boolean().optional(),
    error: z.string().optional()
  }).strict(),
  cache: z.object({
    enabled: z.boolean(),
    path: z.string()
  }).strict(),
  next_steps: z.array(z.string())
}).strict();

export const SummaryOutputSchema = z.object({
  kind: z.enum(["daily_summary", "weekly_summary"]),
  generated_at: z.string()
}).passthrough();

export type CollectionInput = z.infer<typeof CollectionInputSchema>;
export type IdInput = z.infer<typeof IdInputSchema>;
export type SimpleReadInput = z.infer<typeof SimpleReadInputSchema>;
export type ResponseOnlyInput = z.infer<typeof ResponseOnlyInputSchema>;
export type AuthUrlInput = z.infer<typeof AuthUrlInputSchema>;
export type ExchangeCodeInput = z.infer<typeof ExchangeCodeInputSchema>;
export type DailySummaryInput = z.infer<typeof DailySummaryInputSchema>;
export type WeeklySummaryInput = z.infer<typeof WeeklySummaryInputSchema>;
