import { z } from "zod";
import { DEFAULT_LIMIT, DEFAULT_MAX_PAGES, MAX_PAGES, MAX_WHOOP_LIMIT } from "../constants.js";

export const ResponseFormatSchema = z.enum(["markdown", "json"]).default("markdown");

export const DateTimeSchema = z.string()
  .datetime({ offset: true })
  .optional()
  .describe("ISO 8601 date-time with timezone, e.g. 2026-04-30T00:00:00Z");

export const CollectionInputSchema = z.object({
  start: DateTimeSchema,
  end: DateTimeSchema,
  limit: z.number().int().min(1).max(MAX_WHOOP_LIMIT).default(DEFAULT_LIMIT)
    .describe("WHOOP page size. WHOOP allows a maximum of 25."),
  next_token: z.string().optional().describe("WHOOP pagination token returned by a previous call."),
  all_pages: z.boolean().default(false).describe("Fetch multiple pages up to max_pages."),
  max_pages: z.number().int().min(1).max(MAX_PAGES).default(DEFAULT_MAX_PAGES)
    .describe("Maximum pages to fetch when all_pages is true."),
  response_format: ResponseFormatSchema
}).strict();

export const IdInputSchema = z.object({
  id: z.union([z.string().min(1), z.number().int().positive()]).describe("WHOOP resource id."),
  response_format: ResponseFormatSchema
}).strict();

export const AuthUrlInputSchema = z.object({
  state: z.string().max(500).optional().describe("Optional OAuth state value generated by the caller."),
  scopes: z.array(z.string()).optional().describe("Optional scope override. Defaults to all read-only WHOOP scopes used by this server."),
  response_format: ResponseFormatSchema
}).strict();

export const ExchangeCodeInputSchema = z.object({
  code: z.string().min(1).describe("OAuth authorization code, or a full redirect URL containing ?code=..."),
  response_format: ResponseFormatSchema
}).strict();

export type CollectionInput = z.infer<typeof CollectionInputSchema>;
export type IdInput = z.infer<typeof IdInputSchema>;
export type AuthUrlInput = z.infer<typeof AuthUrlInputSchema>;
export type ExchangeCodeInput = z.infer<typeof ExchangeCodeInputSchema>;
